// Isabelle symbol table: \<name> <-> Unicode, plus ASCII abbreviations used by Isabelle/jEdit.

export const SYMBOLS: Record<string, string> = {
  forall: '∀',
  exists: '∃',
  nexists: '∄',
  lambda: 'λ',
  and: '∧',
  or: '∨',
  not: '¬',
  longrightarrow: '⟶',
  Longrightarrow: '⟹',
  longleftrightarrow: '⟷',
  Longleftrightarrow: '⟺',
  longleftarrow: '⟵',
  Longleftarrow: '⟸',
  rightarrow: '→',
  Rightarrow: '⇒',
  leftarrow: '←',
  Leftarrow: '⇐',
  leftrightarrow: '↔',
  mapsto: '↦',
  And: '⋀',
  Or: '⋁',
  equiv: '≡',
  noteq: '≠',
  le: '≤',
  ge: '≥',
  lless: '≪',
  in: '∈',
  notin: '∉',
  subset: '⊂',
  subseteq: '⊆',
  supset: '⊃',
  supseteq: '⊇',
  union: '∪',
  inter: '∩',
  Union: '⋃',
  Inter: '⋂',
  times: '×',
  circ: '∘',
  cdot: '⋅',
  open: '‹',
  close: '›',
  lbrakk: '⟦',
  rbrakk: '⟧',
  langle: '⟨',
  rangle: '⟩',
  lparr: '⦇',
  rparr: '⦈',
  bottom: '⊥',
  top: '⊤',
  turnstile: '⊢',
  Turnstile: '⊨',
  alpha: 'α',
  beta: 'β',
  gamma: 'γ',
  delta: 'δ',
  epsilon: 'ε',
  zeta: 'ζ',
  eta: 'η',
  theta: 'θ',
  iota: 'ι',
  kappa: 'κ',
  mu: 'μ',
  nu: 'ν',
  xi: 'ξ',
  pi: 'π',
  rho: 'ρ',
  sigma: 'σ',
  tau: 'τ',
  phi: 'φ',
  chi: 'χ',
  psi: 'ψ',
  omega: 'ω',
  Gamma: 'Γ',
  Delta: 'Δ',
  Theta: 'Θ',
  Lambda: 'Λ',
  Sigma: 'Σ',
  Phi: 'Φ',
  Psi: 'Ψ',
  Omega: 'Ω',
  nat: 'ℕ',
  int: 'ℤ',
  rat: 'ℚ',
  real: 'ℝ',
  comment: '—',
  bullet: '•',
  infinity: '∞',
  emptyset: '∅',
  sharp: '♯',
  some: 'ε',
  index: 'ı',
  dots: '…',
  sqsubseteq: '⊑',
  sqinter: '⊓',
  squnion: '⊔',
  oplus: '⊕',
  otimes: '⊗',
  sum: '∑',
  prod: '∏',
  bar: '¦',
  'hyphen': '‐',
};

const UNI_TO_NAME: Record<string, string> = {};
for (const [k, v] of Object.entries(SYMBOLS)) if (!(v in UNI_TO_NAME)) UNI_TO_NAME[v] = k;
UNI_TO_NAME['ε'] = 'epsilon';

/** Convert \<name> sequences to Unicode. */
export function decodeSymbols(s: string): string {
  return s.replace(/\\<([A-Za-z]+)>/g, (m, name: string) => SYMBOLS[name] ?? m);
}

/** Convert Unicode symbols to \<name> (for exporting .thy files usable by real Isabelle). */
export function encodeSymbols(s: string): string {
  let out = '';
  for (const ch of s) {
    const n = UNI_TO_NAME[ch];
    out += n ? `\\<${n}>` : ch;
  }
  return out;
}

/** ASCII abbreviations that Isabelle/jEdit replaces as you type, mapped to symbols. */
export const ABBREVIATIONS: [string, string][] = [
  ['==>', '⟹'],
  ['<==>', '⟺'],
  ['-->', '⟶'],
  ['<-->', '⟷'],
  ['<->', '↔'],
  ['=>', '⇒'],
  ['->', '→'],
  ['<-', '←'],
  ['!!', '⋀'],
  ['/\\', '∧'],
  ['\\/', '∨'],
  ['~=', '≠'],
  ['<=', '≤'],
  ['>=', '≥'],
  ['[|', '⟦'],
  ['|]', '⟧'],
  ['<<', '‹'],
  ['>>', '›'],
  ['==', '≡'],
  ['%', 'λ'],
  ['ALL', '∀'],
  ['EX', '∃'],
  [':~', '∉'],
];

/** Named completions offered by the editor (typing \forall etc.) */
export const COMPLETIONS: { label: string; sym: string; detail: string }[] = Object.entries(SYMBOLS).map(([k, v]) => ({
  label: '\\' + k,
  sym: v,
  detail: `\\<${k}>`,
}));

/** Symbols shown on the on-screen symbol bar (mobile friendly). */
export const SYMBOL_BAR: { sym: string; title: string }[] = [
  { sym: '⟹', title: 'meta implication \\<Longrightarrow> (==>)' },
  { sym: '⟶', title: 'implication \\<longrightarrow> (-->)' },
  { sym: '∀', title: 'for all \\<forall>' },
  { sym: '∃', title: 'exists \\<exists>' },
  { sym: 'λ', title: 'lambda \\<lambda>' },
  { sym: '∧', title: 'and \\<and> (/\\)' },
  { sym: '∨', title: 'or \\<or> (\\/)' },
  { sym: '¬', title: 'not \\<not>' },
  { sym: '≠', title: 'not equal \\<noteq>' },
  { sym: '≤', title: 'less or equal \\<le>' },
  { sym: '≥', title: 'greater or equal \\<ge>' },
  { sym: '⟷', title: 'iff \\<longleftrightarrow>' },
  { sym: '⇒', title: 'function type \\<Rightarrow>' },
  { sym: '⋀', title: 'meta forall \\<And>' },
  { sym: '‹', title: 'open cartouche \\<open>' },
  { sym: '›', title: 'close cartouche \\<close>' },
  { sym: '⟦', title: '\\<lbrakk>' },
  { sym: '⟧', title: '\\<rbrakk>' },
  { sym: '∈', title: 'member \\<in>' },
  { sym: '∉', title: 'not member \\<notin>' },
  { sym: '∪', title: 'union \\<union>' },
  { sym: '∩', title: 'intersection \\<inter>' },
  { sym: '⊆', title: 'subset \\<subseteq>' },
  { sym: '×', title: 'product \\<times>' },
  { sym: '∘', title: 'composition \\<circ>' },
  { sym: '≡', title: 'definitional equality \\<equiv>' },
  { sym: '"', title: 'double quote' },
  { sym: '#', title: 'list cons' },
  { sym: '@', title: 'list append' },
  { sym: '[]', title: 'empty list' },
];
