import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 }, colorScheme: 'dark' });
const page = await ctx.newPage();
await page.goto('http://localhost:4173/ide/');
await page.getByText('All checked ✓').first().waitFor({ timeout: 30000 });
await page.locator('.cm-line', { hasText: 'apply (induction n)' }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: process.argv[2] });
await browser.close();
